### ISSUE TITLE
[Dev] Nicely fits to different window widths

### ISSUE THREAD

**Issue by BRaimbault** [MSF-UK/MSF-Dashboard#19]
Starts with #20

**Comment by BRaimbault** [comment]
Add the possibility to hide the lateral menu?

**Comment by idrissait** [comment]
Why not if easy enough. Mostly for graph to be seen properly on the screen also for export.

**Comment by idrissait** [comment]
Fixed, no?

**Comment by heidieh** [comment]
Initial zoom level set depending on screen dimensions
