### ISSUE TITLE
[Dev] Adapt chart and map size to field laptop at fullHD resolution

### ISSUE THREAD

**Issue by idrissait** [MSF-UK/MSF-Dashboard#20]
field laptop are HP elitebook 840 with 1920*1080 resolution. half screen is currently empty.
Need to validate if user change windows OS size to increase the typo (often the case)

**Comment by idrissMSF** [comment]
field laptop are HP elitebook 840 with 1920*1080 resolution. half screen is currently empty.
Need to validate if user change windows OS size to increase the typo (often the case)

**Comment by idrissait** [comment]
Duplicate with issue #19

**Comment by BRaimbault** [comment]
Should be done.
@idrissMSF I'll give you a link for testing when I put everything online.
