### ISSUE TITLE
[Dev] Limit display period to 53 weeks

### ISSUE THREAD

**Issue by BRaimbault** [MSF-UK/MSF-Dashboard#23]
@idrissMSF Instead of limiting to 53 weeks I'd better suggest to use the same approach as here: https://braimbault.github.io/dc_ERCS-DHIS/ where a third bar chart permits to focus the two others on a specific period (it should have a smaller height than in the example - not made to visualize but just to select). 
If we just don't display the earlier weeks, we then should not display them on the map, but it might be interesting to compare maps of different years... if we want to be able to map earlier weeks it gets confusing not to have them on the bar chart.
Is that understandable? What do you think?

**Comment by idrissait** [comment]
As a weekly analysis, you need the latest 53 weeks.
But at the same time, you need the same period for each year (the per year).
I would limit to the last 53 weeks and current year for visualisation including the map.
But as you go per year, it changes...

**Comment by idrissait** [comment]
Limit label shown to 1/4-5 or per month
