### ISSUE TITLE
[Dev] Display lvl5 in data table

### ISSUE THREAD

**Issue by idrissait** [MSF-UK/MSF-Dashboard#36]

**Comment by BRaimbault** [comment]
Changes:
Katanga cfg: https://github.com/MSF-UK/MSF-Dashboard/commit/4e300715fad46742a650a903f915871328bd86b0
SudKivu cfg: https://github.com/MSF-UK/MSF-Dashboard/commit/c941019d127be5fd44c036a57f71b42b89967406

Not pushed to releases.
