### ISSUE TITLE
 [Dev]The Epi Weeks labels on graphs are too small to read on the screen

### ISSUE THREAD

**Issue by idrissait** [MSF-UK/MSF-Dashboard#38]
Automatic display according to scale.

If 53 weeks->every 4th [4,8,12,16,20,24,28,32,36,40,44,48,52]
If below XX weeks, display each epiweek then.

**Comment by heidieh** [comment]
Done as stipulated above. Ideally, the number of ticks displayed should depend on the length of the axis though.
