### ISSUE TITLE
[Bug] Blank space in integer field causes "NaN" in key figures

### ISSUE THREAD

**Issue by idrissait** [MSF-UK/MSF-Dashboard#45]
Under ‘Key figures’ on the far left, ‘Deaths’ no longer shows a number but says ‘NaN’ (recent issue)

On standby for now>
To check with their current database first.

**Comment by BRaimbault** [comment]
I cannot reproduce the issue with the latest version.

**Comment by BRaimbault** [comment]
Blank spaces will cause "Key figures" to show NaNs.
Likely to affect all dashboards.
Filter for numeric values should be double checked.

**Comment by heidieh** [comment]
Fixed
