### ISSUE TITLE
[update] Update catchment areas in DHMT (points to area)

### ISSUE THREAD

**Issue by idrissait** [MSF-UK/MSF-Dashboard#51]
Shapefile with Idriss

**Comment by BRaimbault** [comment]
You probably can do it yourself, the only thing to be careful with is the "name" in the property object of each feature when converting to geojson. 
The convention is:
`name: name_of_adm1_feature, name_of_adm2_feature`

And this is the file to replace: https://github.com/MSF-UK/MSF-Dashboard/blob/master/cfg_dhmt-tonkolili/data/geo_phu.geojson keep the filename or change it here: https://github.com/MSF-UK/MSF-Dashboard/blob/master/cfg_dhmt-tonkolili/dev/dev-defined.js#L124

Good luck!
